name: fahd_lg_remote
description: FAHD LG webOS TV remote + cast - premium dark UI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  network_info_plus: any
  permission_handler: any
  audioplayers: any

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
